version: '3'

services:
  db:
    image: postgres:15.3
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    container_name: ${CONTAINER_NAME}
    volumes:
      - ${POSTGRES_VOLUME}:/var/lib/postgresql/data
  redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"
    container_name: siget-redis
    volumes:
      - redis:/data

volumes:
  redis: